### ISSUE TITLE
Source info 

### ISSUE THREAD

**Issue by alyfreym** [DerekSelander/symbol-interposing#1]
Hi, Where I can find a book that contains these topics? Chapter 1, 2 ... 16. Or it is simple articles posted on Medium or something like that

**Comment by DerekSelander** [comment]
Hey @alyfreym it depends what you are interested in learning more about. Happy to suggest resources if you specify what components you are interested in

**Comment by DerekSelander** [comment]
This was originally written for a book that I don't have time finishing.
